apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ui-server
  namespace: kubeops
spec:
  interval: 30m
  releaseName: kube-ui-server
  chart:
    spec:
      chart: kube-ui-server
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
  values:
    {{- .Values | toYaml | nindent 4}}
