{{ if .Values.kubePrometheusStack.create }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "40.3.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    labels:
    {{ range $k,$v := .Values.kubePrometheusStack.labels}}
        {{ "$k: $v" | nindent 6}}
    {{ end }}
{{ end }}
