# Docker registry fqdn used to pull docker images
# Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
registryFQDN: ""
image:
  # Docker registry used to pull operator image
  registry: appscode
  # Name of operator container image
  repository: kube-ui-server